### ISSUE TITLE
Write script to convert transcript from txt to json

### ISSUE THREAD

**Issue by agarrharr** [orbitfm/orbit.fm#106]
Create a script written in any language that I can run once per episode. I prefer node. There is no need to run the gatsby project in order to complete this issue. It can be a stand alone script, but it should be unit tested.

Here is an example txt transcript:

[BookBytes Episode 15.txt](https://github.com/orbitfm/orbit.fm/files/2436198/BookBytes.Episode.15.txt)

And here is what the json should look like: https://github.com/orbitfm/orbit.fm/blob/master/transcripts/bb-014.json

### Timestamp, speaker, and text

```
0:24:19.9 ***Adam Garrett-Harris & Jason Staten** (laughing)
```

Should become:
```
{
  "timestamp": "0:24:19.9",
  "speaker": "Adam Garrett-Harris & Jason Staten",
  "text": "(laughing)"
},
```

### Timestamp and text

```
0:00:41.0 (Intro music: Electro swing) 
```

Should become:

```
{
  "timestamp": "0:00:41.0",
  "text": "(Typewriter dings)"
},
```

## Parenthesis

Lines that start and end with a parenthesis:

```
(Intro music: Electro swing) 
```

Should become:

```
{
  "text": "(Typewriter dings)"
},
```

## Errors

Anything else should be ignored, but printed out as an error:

```
________________
```

```
Error: Unknown format on line 16: "________________"
```

**Comment by reiff12** [comment]
I can do this!

**Comment by agarrharr** [comment]
Awesome! This will be super useful!

**Comment by jakesmithdeveloper** [comment]
I've created a Node script just for some practice with node #110

**Comment by agarrharr** [comment]
Cool. Can you write some unit tests for it?

**Comment by jakesmithdeveloper** [comment]
@agarrharr I've never written unit tests with Node, I'll look into it after I finish my school work.
