### ISSUE TITLE
Add host and guest images next to name in the transcript

### ISSUE THREAD

**Issue by agarrharr** [orbitfm/orbit.fm#111]
There should be a very small image next to everyone's name in the transcript.

The code is in `src/templates/episode.js`

1. Add image to graphql query for the `contentfulEpisode`
2. Use that image next to each person's name

**Comment by mohinderps** [comment]
Can I take this?

**Comment by agarrharr** [comment]
@mohinderps Yeah, that would be great! Let me know if you have any questions.

**Comment by mohinderps** [comment]
Created PR #113. Do let me know of any amendments.

**Comment by mohinderps** [comment]
Okay, sorry. I did something else. Let me redo it.

**Comment by agarrharr** [comment]
Ok, sounds good!

**Comment by mohindersaluja** [comment]
Hey @agarrharr, A sample transcript contains below speaker names.

1: "Adam Garrett-Harris"
2: "Safia Abdalla"
3: "Jen Luker"
4: "Jason Staten"
5: "Adam Garrett-Harris & Jason Staten"
6: "ALL"
7: "Jen Luker & Safia Abdalla & Adam Garrett-Harris"
8: "Safia Abdalla & Jason Staten & Adam Garrett-Harris"
9: "*Jen Luker"
10: "*Adam Garrett-Harris & Jason Staten"
11: "Jen Luker & Safia Abdalla"
12: null

How do I handle cases 5, 6, 9 and 10?

**Comment by mohinderps** [comment]
Sorry, that was my another id. Yeah, So how do I handle the above mentioned cases?

**Comment by agarrharr** [comment]
Well, the ones with asterisks are an error. You can ignore them and show no image. The ones with multiple names separated with & might be a little tricky. I think it should show all those people, but perhaps overlapped like it does on GitHub when multiple people are on a commit.

**Comment by mohinderps** [comment]
Please share the screenshot of the same, so that we are on the same page.

**Comment by agarrharr** [comment]
Here is a link to an example: https://github.com/lifestonechurch/lifestonechurch.net/commits/master

<img width="552" alt="screen shot 2018-10-04 at 10 44 47 am" src="https://user-images.githubusercontent.com/3266363/46489428-9a3be700-c7c2-11e8-80ce-99a367a8e3a2.png">

**Comment by mohinderps** [comment]
Okay, will do the same.

**Comment by agarrharr** [comment]
And for ALL, you can just show no image.

**Comment by mohinderps** [comment]
Hey @agarrharr, I have added PR #115. Do let me know of any changes.
