### ISSUE TITLE
Upgrade to Gatsby 2.x

### ISSUE THREAD

**Issue by agarrharr** [orbitfm/orbit.fm#114]
Gatsby 2.0 is out, and all of the gatsby dependencies should be updated to `2.x` instead of `next`.

**Comment by VagishVela** [comment]
I'd be happy to do this! Feel free to assign this to me if you want me to do it.

**Comment by agarrharr** [comment]
Thanks! It looks like I can't assign you on GitHub because I can only assign contributors or team members. But it would be great if you could do this. 👍
