### ISSUE TITLE
Add contact page

### ISSUE THREAD

**Issue by agarrharr** [orbitfm/orbit.fm#12]

**Comment by knittingcodemonkey** [comment]
Do we need a contact page? We just say tweet the podcast, or have twitter links somewhere.

**Comment by agarrharr** [comment]
We don't really need it probably. It's just another way for people to get in touch in case they don't have Twitter.

**Comment by knittingcodemonkey** [comment]
Perhaps. I just like to avoid contact forms if at all possible. If we have an email posted, lets be careful to use the `email at this dot com` format to avoid getting spammed?

**Comment by agarrharr** [comment]
Yeah, makes sense. I was going to look into one of these form options: https://github.com/agarrharr/awesome-static-website-services#forms

**Comment by knittingcodemonkey** [comment]
Perhaps we leave it to the end? It's really the least important feature, for now.

**Comment by agarrharr** [comment]
I would use Contentful forms for this like I did with the giveaway page.
