### ISSUE TITLE
Fix flicker on first render

### ISSUE THREAD

**Issue by agarrharr** [orbitfm/orbit.fm#92]
When the page first loads, it loads without css. This needs to be fixed so that it doesn't flicker.

**Comment by statianzo** [comment]
Can emotion be put into static mode so CSS gets loaded before JS?

**Comment by agarrharr** [comment]
Yeah, something like that. I know it can load critical css earlier.

**Comment by agarrharr** [comment]
Mostly fixed in 4c641431a94b8a20d73dfd7da0064fcf8168f336 and 01a23bdceaf09a99863e53c1a6d9f0571396e6a5

But there is still a small FOUC where the links are orange instead of white.
